### ISSUE TITLE
I get an errro while starting the bot, related to teh actual bot, not sure how to fix it, permission problems I think

### ISSUE THREAD

**Issue by juangea** [xNul/chat-llama-discord-bot#14]
This is the error:

Traceback (most recent call last):
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\bot.py", line 400, in <module>
    client.run(bot_args.token if bot_args.token else TOKEN, root_logger=True)
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\discord\client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\discord\client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by xNul** [comment]
@juangea looks like you haven't given enough permissions for the bot to work.Try enabling the privileged intents permissions for your bot token

**Comment by juangea** [comment]
Yeah, that was the problem, I was coming to say so when I saw your answer, thanks!
