### ISSUE TITLE
Hi so many errors, can you help?

### ISSUE THREAD

**Issue by Webslug** [xNul/chat-llama-discord-bot#17]
ERROR:Ignoring exception in command reset
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 370, in reset
    clear_chat_log(your_name, llamas_name, "", "","cai-chat")
TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given
[2023-05-26 00:40:32] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command reset
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 370, in reset
    clear_chat_log(your_name, llamas_name, "", "","cai-chat")
TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given
ERROR:Ignoring exception in command reset
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 370, in reset
    clear_chat_log(your_name, llamas_name, "", "","cai-chat")
TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given
[2023-05-26 00:40:47] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command reset
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 370, in reset
    clear_chat_log(your_name, llamas_name, "", "","cai-chat")
TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'reset' raised an exception: TypeError: clear_chat_log() takes 2 positional arguments but 5 were given

**Comment by xNul** [comment]
Hi, I've just released an update to the bot which should fix all these errors. It's tough keeping up to date with webui because it changes so much.

**Comment by Webslug** [comment]
Thanks for the update however it still does not work even with the amendmants. I keep having the following errors.

ERROR [2023-06-05 13:41:10]: Ignoring exception in on_message (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 485, in on_message
    reaction_choice = reaction_list[random.randrange(8)]
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 372, in llm_gen
    "trust-remote-code": shared.args.trust_remote_code,
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 351, in chatbot_wrapper_wrapper
    "name2": name2,
  File "D:\AI\oobabooga\text-generation-webui\modules\chat.py", line 206, in chatbot_wrapper
    text, visible_text = output['internal'][-1][0], output['visible'][-1][0]
IndexError: list index out of range

I have tried 3 models so far, one was working temporarily but stopped.  

I am now trying the GGML model which you recommended.  This is my last attempt to try and get this working.

I'm ready to give up.  So demoralized.

**Comment by Webslug** [comment]
I decided to try and use your install batch file this time with a fresh install.    I used the GGML model which you recommended.

I followed the instructions carefully and I have a Nvidia card.  My web UI works perfectly.

I kept getting this error and have concluded that this bot no longer works.  

Traceback (most recent call last):
  File "D:\AI\ChatLlama\ChatLLaMA\oobabooga_windows\text-generation-webui\bot.py", line 279, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AI\ChatLlama\ChatLLaMA\oobabooga_windows\text-generation-webui\modules\models.py", line 97, in load_model
    output = load_func(model_name)
  File "D:\AI\ChatLlama\ChatLLaMA\oobabooga_windows\text-generation-webui\modules\models.py", line 265, in llamacpp_loader
    from modules.llamacpp_model import LlamaCppModel
  File "D:\AI\ChatLlama\ChatLLaMA\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 11, in <module>
    from llama_cpp import Llama, LlamaCache
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by xNul** [comment]
that's strange because other people are able to use the new installers without issue. I'm trying to reproduce, but in the meantime, could you try to reinstall once more and this time, copy-paste the install log here? There might be an error with installing the llama_cpp library during installation

**Comment by xNul** [comment]
I've reinstalled with the latest installer, using the GGML model that I recommended, and didn't have any issues (Windows 11 and Nvidia). Don't give up! We'll figure this out. If you prefer to talk about this in real time, you can join my Discord server https://discord.gg/TcRGDV754Y

**Comment by Webslug** [comment]
Well I managed to get it working, thanks for not giving up on me. 

The bot is connecting successfully and processing text so that's great news.  

Is there any way to permanently save the prompt, name and llama name so I do not have to keep typing in the prompt every time I start the bot up?

Thanks again.
