### ISSUE TITLE
Getting errors when trying to run a lammacpp model

### ISSUE THREAD

**Issue by keninishna** [xNul/chat-llama-discord-bot#5]
this model works normally when running server.py
The model loads and the bot connects but when I try the reply command it fails with the following error.

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "/home/user/text-generation-webui/bot.py", line 179, in reply
    await ll_gen(ctx, queues)
  File "/home/user/text-generation-webui/bot.py", line 113, in ll_gen
    for resp in chatbot_wrapper(**user_input):
TypeError: chatbot_wrapper() got an unexpected keyword argument 'check'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/discord/app_commands/commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reply' raised an exception: TypeError: chatbot_wrapper() got an unexpected keyword argument 'check'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/discord/app_commands/commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'reply' raised an exception: TypeError: chatbot_wrapper() got an unexpected keyword argument 'check'

**Comment by keninishna** [comment]
Looks like its unrelated to the new model and just prior changes to code. I change line 100 from:
user_input["check"] = False
to
user_input["stop_at_newline"] = False

and it runs now.

**Comment by xNul** [comment]
@keninishna hey thanks for the bug report. I've fixed this bug and some others that have been created from the updates webui has made. It should run correctly rn.
